__title__ = "facebook_fetcher"
__description__ = "Facebook scraper - Fetcher Unlimited"
__url__ = "https://github.com/Andryerics/facebook_fetcher"
__version__ = "1.0.2"
__author__ = "Åndry RL"
__author_email__ = "andryerics@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright Åndry RL"
